version: '3'
services:
  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017

  mongo_seed:
    image: mongo:latest
    links:
      - mongodb
    volumes:
      - ./mongo-seed:/mongo-seed
    command:
      bash -c "chmod +x /mongo-seed/restore.sh && /mongo-seed/restore.sh"
  redis:
    image: redis:5.0.4-alpine
    ports:
      - '6379:6379'

